# Generated by Django 4.0.4 on 2022-04-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=50)),
                ('player_name', models.CharField(max_length=100)),
                ('high_jump', models.IntegerField()),
                ('long_jump', models.IntegerField()),
            ],
        ),
    ]
